version: '3.8'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - article_search_backend

  web01:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - config.env
    ports:
      - "8081:8080"
    networks:
      - article_search_backend

  web02:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - config.env
    ports:
      - "8082:8080"
    networks:
      - article_search_backend

  haproxy:
    image: haproxy:2.8
    restart: unless-stopped
    depends_on:
      - web01
      - web02
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - article_search_backend

volumes:
  redis-data:

networks:
  article_search_backend: